version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default
    profiles: ["app"]
    links:
      - db
    restart: always

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - database:/var/lib/mysql
    networks:
      - default

networks:
  default:

volumes:
  database:
    name: database
